- hosts: nodes
  become: yes
  gather_facts: True

  tasks:
    - name: include k8s version
      include_vars: /vagrant/ansible-playbook/versions.yml
    - name: include kubeadm join token etc
      include_vars: /vagrant/ansible-playbook/kubeadm-join.yaml

    ## k8sノードをリセット
    #
    - name: kubeadm reset v1.10 or eary
      command: kubeadm reset


    ## k8sクラスタへ参加
    #
    - name: kubeadm join
      command: "{{ join_command }}"
