- hosts: nodes
  become: yes
  gather_facts: True

  tasks:
    - name: include k8s version
      include_vars: /vagrant/ansible-playbook/versions.yml
    - name: include kubeadm join token etc
      include_vars: /vagrant/ansible-playbook/kubeadm-join.yaml

    ## k8sノードをリセット
    #
    - name: kubeadm reset v1.11 or later
      command: kubeadm reset -f
      when: k8s_minor_ver|int >= 11

    - name: kubeadm reset v1.10 or eary
      command: kubeadm reset
      when: (k8s_minor_ver == "10") or (k8s_minor_ver == "9")


    ## k8sクラスタへ参加
    #
    - name: kubeadm join
      command: "{{ join_command }}"


    ## kubeletのDNSのIPアドレスを変更
    #
    - name: change config.yaml
      replace:
        dest: /var/lib/kubelet/config.yaml
        regexp: '10.96.0.10'
        replace: 10.32.0.10
      when: k8s_minor_ver|int >= 11

    ## kubeletをリスタートして変更を反映
    #
    - name: daemon-reload and restart kubelet
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet
      when: k8s_minor_ver|int >= 11

    ## Create directory for Persistent Volume hostpath
    #
    - name: create hostPath vol1 for each node
      file: path=/vol1 state=directory owner=root group=root mode=0755
    - name: create hostPath vol2 for each node
      file: path=/vol2 state=directory owner=root group=root mode=0755
    - name: create hostPath vol3 for each node
      file: path=/vol3 state=directory owner=root group=root mode=0755
    - name: create hostPath vol4 for each node
      file: path=/vol4 state=directory owner=root group=root mode=0755
    - name: create hostPath vol5 for each node
      file: path=/vol5 state=directory owner=root group=root mode=0755
    - name: create hostPath vol6 for each node
      file: path=/vol6 state=directory owner=root group=root mode=0755
    - name: create hostPath vol7 for each node
      file: path=/vol7 state=directory owner=root group=root mode=0755
