- hosts: all
  connection: local
  become: yes
  gather_facts: True
  
  vars:
    #- k8s_version: =1.9.6-00
    #- k8s_version: =1.10.3-00
    - k8s_version:

    #- docker_version: =17.12.1~ce-0~ubuntu
    - docker_version: =17.03.2~ce-0~ubuntu-xenial

  tasks:
  #
  # Docker CE のインストール
  #
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - debug: var={{ansible_distribution_release}}

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install list of packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - nfs-common

  - name: Install Docker-CE
    apt:
      name: docker-ce{{ docker_version }}
      state: present
      update_cache: yes


  - name: usermod -aG docker vagrant
    user:
      name: vagrant
      groups: docker

  #
  # カーネル設定変更
  #
  - name: Set sysctl 
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      sysctl_set: yes
      sysctl_file: /etc/sysctl.conf      
      state: present
      reload: yes

  #
  # GlusterFS のインストール
  #
  - name: Add GlusterFS Repository
    apt_repository:
      repo: ppa:gluster/glusterfs-3.12

  - name: Install GlusterFS
    apt:
      name: glusterfs-server
      state: present
      update_cache: yes


  #
  # Kubernetes のインストール
  #
  - name: add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: add Kubernetes' APT repository
    apt_repository:
     repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
     state: present
     filename: 'kubernetes'

  #- name: Install list of kubernetes packages 
  #  apt:
  #    name: "{{ item }}"
  #    state: present
  #    update_cache: yes
  #  with_items:
  #    - kubeclt{{ k8s_version }}
  #    - kubelet{{ k8s_version }}
  #    - kubeadm{{ k8s_version }}

  - name: Install kubectl
    apt:
      name: kubectl{{ k8s_version }}
      state: present
      update_cache: yes

  - name: Install kubelet
    apt:
      name: kubelet{{ k8s_version }}
      state: present
      update_cache: yes

  - name: Install kubeadm
    apt:
      name: kubeadm{{ k8s_version }}
      state: present
      update_cache: yes


